services:

  backend:
    container_name: backend-macc
    restart: always
    ports:
      - 5001:5001
    build:
      context: ./backend-node
      dockerfile: ./Dockerfile
    volumes:
      - ./backend-node:/code
    networks:
      - main

  mongodb:
    container_name: mongo-macc
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
    logging:
      driver: none
    volumes:
      - macc-data:/data/db
    networks:
    - main

  mongo-express:
    container_name: express-macc
    image: mongo-express:latest
    restart: always
    depends_on:
      - mongodb
    ports:
      - 9300:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: user
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: "27017"
    networks:
      - main

  image-server:
    container_name: image-server-macc
    build:
      dockerfile: ./app/Dockerfile
    ports:
      - 9705:9705
    environment:
    - PYTHONUNBUFFERED=1
    networks:
      - main
    volumes:
      - image-server-data:/app/uploads

volumes:
  macc-data:
  image-server-data:

networks:
  main:
    driver: bridge
